name: universal_file_handler
description: "Universal Flutter file handling with memory cache, disk cache, downloads, asset loading, viewers, and sharing."
version: 0.1.1
homepage: https://github.com/sagar9098/universal_file_handler
license: MIT

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  path_provider: ^2.1.2
  open_filex: ^4.7.0
  share_plus: ^12.0.1
  photo_view: ^0.15.0
  flutter_pdfview: ^1.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:


